### ISSUE TITLE
false-positive: reassign inside an infinite loop and not use after exiting loop

### ISSUE THREAD

**Issue by ldez** [sanposhiho/wastedassign#21]
```go
package main

func main() {
	var err error
	var rest []byte
	for {
		rest, err = bar(rest)

		if err == nil {
			break
		}
	}
}

func bar(d []byte) ([]byte, error) {
	return nil, nil
}
```

```
foo.go:7:3: reassigned, but never used afterwards (wastedassign)
                rest, err = bar(rest)
                ^
```

**Comment by sanposhiho** [comment]
Thanks for your report.

After exiting the loop, `rest` is not used, so it seems to detect that the last assign is `reassigned, but never used afterwards`.

Hmm, This seems to be a difficult problem, because the report made by wastedassign is not wrong. 
It is true that `rest` is reassigned in the loop, used in the loop... and then finally reassigned when exiting the loop is useless.
But for the user, there is no way to fix it...(i.e. to be a good linter `wastedassign` should not report this)

I'll figure out how to deal with this problem.
