### ISSUE TITLE
complex c style for loop false positive 

### ISSUE THREAD

**Issue by carnott-snap** [sanposhiho/wastedassign#27]
The `for` loop in the following `read` function triggers a false positive:
```go
func read(r io.Reader, b []byte) (err error) {
        for i, n := 0, 0; i != len(b); i += n {
                n, err = r.Read(b[i:])
                if err != nil {
                        return err
                }
        }
        return nil
}
``` 

> Yes, I now know that I should just do `io.ReadFull` instead; but the reproducer stands.

**Comment by sanposhiho** [comment]
Hi @carnott-snap.

This issue is solved in [v0.2.0](https://github.com/sanposhiho/wastedassign/releases/tag/v0.2.0).

**If you use golangci-lint**

The version of golangci-lint's wastedassign is now v0.1.3. 
And, it is upgraded to the new version in [this PR](https://github.com/golangci/golangci-lint/pull/1815). Please wait for the next golangci-lint release, which will be fixed to use wastedassign v0.2.0.

Thank you for your report. 👍
