### ISSUE TITLE
Suspected false positive: operator assignment inside loop

### ISSUE THREAD

**Issue by mmcloughlin** [sanposhiho/wastedassign#28]
The following code generates an error for the `s *= 2` statement:

```go
func (FermatStrategy) K(n *big.Int) []*big.Int {
	ks := []*big.Int{}
	k := new(big.Int).Rsh(n, 1)
	one := bigint.One()
	s := uint(1)
	for k.Cmp(one) > 0 {
		ks = append(ks, bigint.Clone(k))
		k.Rsh(k, s)
		s *= 2
	}
	return ks
}
```

https://github.com/mmcloughlin/addchain/blob/3d88f7689d76cd7d9afa7cefaac9a0ab6c5ba3c2/alg/contfrac/contfrac.go#L225

Specifically, when run via `golangci-lint` version 1.38.0 I see:

```
alg/contfrac/contfrac.go:225:3: reassigned, but never used afterwards (wastedassign)
		s *= 2
		^
```

I believe this is a false positive.

**Comment by sanposhiho** [comment]
Hi @mmcloughlin.

This issue is solved in [v0.2.0](https://github.com/sanposhiho/wastedassign/releases/tag/v0.2.0).

The version of golangci-lint's wastedassign is now v0.1.3. 
And, it is upgraded to the new version in [this PR](https://github.com/golangci/golangci-lint/pull/1815). Please wait for the next golangci-lint release, which will be fixed to use wastedassign v0.2.0.

Thank you for your report. 👍
